version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/thirty-challenge"  # adjust if your package.json is deeper
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2

    groups:
      dependencies:
        patterns:
          - "*"

    ignore:
      - dependency-name: "react"
        versions: ["<18.0.0"]

    # Enable auto-merge (optional, off by default)
    # auto-merge: true  # uncomment to enable

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
    groups:
      github-actions:
        patterns:
          - "*"
