[build]
  base       = "thirty-challenge"
  command    = "npm run build"
  publish    = "dist"
  environment = {
    VITE_COMMIT_REF = "$COMMIT_REF",
    NODE_VERSION    = "18"
  }

[functions]
  directory    = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
