[build]
  base = "thirty-challenge"
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Environment variables are set in Netlify UI
  # Disable secrets scanning since VITE_ variables are meant to be public
  SECRETS_SCAN_ENABLED = "false"