[build]
  base = "thirty-challenge"
  command = "npm ci && npm run build"
  publish = "dist"
  environment = { SECRETS_SCAN_ENABLED = "false" }

# Context-specific settings
[context.production]
  command = "npm ci && npm run build"
  environment = { SECRETS_SCAN_ENABLED = "false" }

[context.deploy-preview]
  command = "npm ci && npm run build"
  environment = { SECRETS_SCAN_ENABLED = "false" }

[context.branch-deploy]
  command = "npm ci && npm run build"
  environment = { SECRETS_SCAN_ENABLED = "false" }