[build]
  base = "thirty-challenge"
  command = "npm run build"
  publish = "dist"
  # Re-export read-only Netlify vars so they're visible to the client bundle
  environment = { VITE_COMMIT_REF = "$COMMIT_REF" }

[functions]
  node_bundler = "esbuild"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200