[build]
  base = "thirty-challenge"
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Environment variables are set in Netlify UI

# Configure secrets scanning to ignore example files
[build.processing.secrets]
  omit_paths = [".env.example"]