openapi: 3.1.0
info:
  title: Dependency Checker
  description: Analyzes file relationships (imports and importedBy) in the GitHub project to prevent broken references during edits.
  version: 1.0.0

tags:
  - name: Dependency Graph
    description: View dependencies and reverse imports for a given file.

servers:
  - url: https://ai.tyshub.xyz
    description: Hosted server on Render

paths:
  /dependencies:
    get:
      tags:
        - Dependency Graph
      operationId: getFileDependencies
      summary: Get both dependencies and files that import the given file
      parameters:
        - name: path
          in: query
          required: true
          description: Relative path to the file (e.g. src/pages/Quiz.tsx)
          schema:
            type: string
      responses:
        '200':
          description: File dependency and usage information
          content:
            application/json:
              schema:
                type: object
                properties:
                  file:
                    type: string
                  dependencies:
                    type: array
                    items:
                      type: string
                  importedBy:
                    type: array
                    items:
                      type: string
