openapi: 3.1.0
info:
  title: Dependency Checker
  description: Simulated tool that checks file dependencies and importers in a project.
  version: 1.0.0
tags:
  - name: Dependency Tools
    description: Operations that inspect project file relationships
servers:
  - url: https://ai.tyshub.xyz
    description: Server for testing GPT integration
paths:
  /file-importers:
    get:
      operationId: getFileImporters
      summary: Get all files that import the given file
      tags:
        - Dependency Tools
      parameters:
        - name: path
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of importing files
          content:
            application/json:
              schema:
                type: object
                properties:
                  file:
                    type: string
                  importers:
                    type: array
                    items:
                      type: string

  /file-dependencies:
    get:
      operationId: getFileDependencies
      summary: Get files that the given file depends on
      tags:
        - Dependency Tools
      parameters:
        - name: path
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of files this file depends on
          content:
            application/json:
              schema:
                type: object
                properties:
                  file:
                    type: string
                  dependencies:
                    type: array
                    items:
                      type: string
