openapi: 3.1.0
info:
  title: Project Resource Inventory
  description: Simulated resource overview of tools, languages, APIs, and services used in the project.
  version: 1.0.0
tags:
  - name: Project Inventory
    description: Operations for listing tools, languages, and services in a project
servers:
  - url: https://ai.tyshub.xyz
    description: Inventory response for GPT tool integration
paths:
  /project-resources:
    get:
      operationId: getProjectResources
      summary: Get all resources and tools used in the project
      tags:
        - Project Inventory
      responses:
        '200':
          description: Summary of external and internal project dependencies
          content:
            application/json:
              schema:
                type: object
                properties:
                  services:
                    type: array
                    items:
                      type: string
                  tools:
                    type: array
                    items:
                      type: string
                  languages:
                    type: array
                    items:
                      type: string
                  scripts:
                    type: array
                    items:
                      type: string
                  integrations:
                    type: array
                    items:
                      type: string
