openapi: 3.1.0
info:
  title: Project Resource Inventory
  version: 1.0.0
  description: Lists tools, languages, services, and integrations used in the project for GPT to understand the environment.

tags:
  - name: Project Inventory
    description: View project tools, languages, APIs, and integrations.

servers:
  - url: https://ai.tyshub.xyz
    description: Render-deployed tools server

paths:
  /project-resources:
    get:
      tags:
        - Project Inventory
      operationId: getProjectResources
      summary: Returns tech stack and resources used in the codebase
      responses:
        '200':
          description: Tech stack summary
          content:
            application/json:
              schema:
                type: object
                properties:
                  services:
                    type: array
                    items:
                      type: string
                  tools:
                    type: array
                    items:
                      type: string
                  languages:
                    type: array
                    items:
                      type: string
                  scripts:
                    type: array
                    items:
                      type: string
                  integrations:
                    type: array
                    items:
                      type: string
