[build]
  # How to build your Vite app
  command    = "npm run build"
  # Where Vite outputs the production files
  publish    = "dist"
  # Pin Functions & build to Node 18
  environment = { NODE_VERSION = "18" }

[functions]
  # Relative to the netlify.toml file (inside thirty-challenge/)
  directory    = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  # Single‑page app fallback — serves index.html for all non‑function URLs
  from   = "/*"
  to     = "/index.html"
  status = 200
