[build]
  base       = "thirty-challenge"
  command    = "npm run build"
  publish    = "dist"
  environment = { NODE_VERSION = "18" }

[functions]
  # point _one level above_ thirty‑challenge
  directory    = "../netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  # send function calls to the true functions
  from = "/.netlify/functions/*"
  to   = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  # then your SPA catch‑all
  from   = "/*"
  to     = "/index.html"
  status = 200
