name: Generate Dependency Map

on:
  workflow_dispatch:  # Enables "Run workflow" button
  push:
    paths:
      - 'src/**'
      - 'package.json'
      - 'vite.config.ts'
      - 'netlify/functions/**'        # Include your Netlify serverless functions
      - 'thirty-challenge/src/**'     # If your src is nested inside this folder
      - 'thirty-challenge/netlify/**' # Any other custom folder you want to track
      - '.github/workflows/madge-dependency-map.yml' # To regenerate if workflow is changed

jobs:
  madge:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./thirty-challenge

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        
      - name: clean up
        run: rm -f full-dependency-map.json

      
      - name: Run Madge and generate JSON
        run: npx madge src --extensions ts,tsx --json > full-dependency-map.json

      - name: Commit and push dependency map (if changed)
        run: |
          cd thirty-challenge
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add full-dependency-map.json
          
          # Ensure full history (fix for shallow clone issues)
          git fetch --unshallow || true
      
          # Stage the updated file
          git add full-dependency-map.json
      
          # Check if anything has changed
          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
          else
            echo "🔄 Changes detected. Committing..."
            git commit -m "chore: update dependency map"
            git push
          fi

