name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
