name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: thirty-challenge

      - name: TypeScript type check
        run: npx tsc --noEmit
        working-directory: thirty-challenge

      - name: Run ESLint
        run: npm run lint
        working-directory: thirty-challenge

      - name: Run Tests
        run: npm test
        working-directory: thirty-challenge